baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "nl-nl"
title = "VVD Dalfsen gemeenteraadsverkiezingen 2026"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""
  favicon = "favicon-vvd.svg"

  [params.homepage]
    sticky_header = true
    show_contact_box = false      # show / hide the contaxt box on the homepage
    show_services_button = false # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo-vvd.svg"
    mobile_height = "36px"
    desktop = "images/logo/logo-vvd.svg"
    desktop_height = "72px"
    alt = "VVD Dalfsen"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#f50"
    secondprimary = "#0A2CCA"
    black = "#1d1d1d"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#0A2CCA"

  [params.seo]
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"
    meta_og_image = "https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png"

  [params.programma]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'VVD Dalfsen'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Verkiezingsprogramma 2026"
    url = "/programma/"
    weight = 1

  [[menu.main]]
    name = "Onze Mensen"
    url = "/team/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
    weight = 2
